### ISSUE TITLE
Error after building from source.

### ISSUE THREAD

**Issue by KoBruh** [secretlay3r/Dividence#2]
Hey, followed the tutorial, obfuscated the code, installed all dependencies, but after compiling source code i get the error 

```Traceback (most recent call last):
  File "<frozen __main__>", line 3, in <module>
  File "<frozen main>", line 1, in <module>
ModuleNotFoundError: No module named 'keyboard'
[PYI-16636:ERROR] Failed to execute script 'main' due to unhandled exception!```

**Comment by secretlay3r** [comment]
> Hey, followed the tutorial, obfuscated the code, installed all dependencies, but after compiling source code i get the error 
> 
> ```Traceback (most recent call last):
>   File "<frozen __main__>", line 3, in <module>
>   File "<frozen main>", line 1, in <module>
> ModuleNotFoundError: No module named 'keyboard'
> [PYI-16636:ERROR] Failed to execute script 'main' due to unhandled exception!```
> 
> 

Run ```
pip install keyboard
``` in cmd, sorry I probably forgor to add keyboard to dependencies

**Comment by KoBruh** [comment]
no you added them , its on me, the obfuscation used just didnt work
